### ISSUE TITLE
如何提升 inference 的速度？

### ISSUE THREAD

**Issue by 394781865** [rmalav15/Super-SloMo#1]
你的工作很棒！但是我想提升 inference 的速度。
我有两个思路：1、使用多GPU进行推理；2、替换vgg19为一个轻量级网络和缩减unet层数。
请问我的方案可行吗？还有你有什么建议吗？

**Comment by 394781865** [comment]
论文作者使用U-Net架构计算输入图像之间的双向光流，使用另一个U-Net来改进近似光流并预测软可见性图。请问你的vgg19用来做什么的？

**Comment by rmalav15** [comment]
If you are planning to use GPU, then removing layers from VGG and UNet may not affect the inference time that much (as we are just doing forward pass). If you are particularly concerned about inference time, use multi-threading.
https://stackoverflow.com/questions/38694111/is-it-thread-safe-when-using-tf-session-in-inference-service
Hope this helps.

Thanks,
Ram
