### ISSUE TITLE
ValueError: The channel dimension of the inputs should be defined. Found `None`.

### ISSUE THREAD

**Issue by 205418367** [rmalav15/Super-SloMo#2]
#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=0 python3 slomo_video.py \
    --input_video_path videos/football.mp4 \
    --output_video_path videos/football_slomo.mp4 \
    --slomo_rate 2 \
    --fps_rate 5 \
    --checkpoint /home/lichen/Super-SloMo/models/slomo-tensorflow-model

当我执行上面的命令时报错？请问是什么原因呢？

**Comment by rmalav15** [comment]
Hi,

If you haven't solved the issue already, You need to give the "video folder path", not "video path".

Thanks,
Ram

**Comment by rmalav15** [comment]
Did you solve it?
Thanks,
Ram

**Comment by 394781865** [comment]
yes, using tensorflow == 1.12
